site_name: Wirewolves' Documentation
site_url: https://docs.wirewolves.org
repo_url: https://github.com/wirewolves10679/Documentation
edit_uri: edit/main/docs/
site_description: >-
  Official documentation site of FRC Team 10679 Wirewolves.

# copyright: >
#   Copyright &copy; 2016 - 2024 Martin Donath –
#   <a href="#__consent">Change cookie settings</a>

plugins:
  - git-revision-date-localized
  - privacy
  - search

theme:
  name: material
  highlightjs: true

  hljs_languages:
    - java
    - yaml
  
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - offline
    - search
    - search.boost
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    # Automatic mode — now with team colors
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  
  icon:
    edit: material/pencil
    repo: fontawesome/brands/github
    view: material/eye

extra:
  version:
    provider: mike

extra_css:
  - stylesheets/colors.css

nav:
  - Home: index.md
  - Business:
      - business/index.md
      - test: business/business.md
  - Electrical:
      - electrical/index.md
      - test: electrical/electrical.md
  - Hardware:
      - hardware/index.md
      - test: hardware/hardware.md
  - Safety:
      - safety/index.md
      - test: safety/safety.md
  - Software:
      - software/index.md
      - test: software/software.md