site_name: Wirewolves' Documentation
site_url: https://docs.wirewolves.org
repo_url: https://github.com/wirewolves10679/Documentation
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - About: about.md
  
plugins:
  - git-revision-date-localized
  - privacy

theme:
  name: material

  highlightjs: true

  hljs_languages:
    - java
    - yaml
  
  features:
    - content.action.edit
    - header.autohide
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.tracking
    - offline
    - toc.follow
    - toc.integrate
    - search
    - search.boost
    - search.highlight
    - search.share
    - search.suggest

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  primary: custom
  
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

extra:
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

# copyright: >
#   Copyright &copy; 2016 - 2024 Martin Donath –
#   <a href="#__consent">Change cookie settings</a>